add info
polkadot-cloud/library pull request #5
Opened 2023-11-17 15:11 UTC by wirednkod

2023-12-05 07:47 UTC, rossbulat requested changes
This solution clones and persists data from `paritytech/polkadot_network_directory`, which is not what we want to do. We want this data in the package, but not duplicate it in source code. Not only are we not maintaining this data, the community will be confused as to its origins.

Instead, as a part of the `assets` package build process, data should fetched from `paritytech/polkadot_network_directory`, formatted into JSON as is done in this current solution, and package it in `dist`. Thereafter these temporary files should be deleted.

2023-12-05 07:49 UTC, rossbulat commented on app/src/docs/Assets/Networks/main.tsx
- @joeljkrb we are yet to discuss but one of the tasks I had in mind for you is to review docs and ensure the grammar and presentation is of a high quality. This is a good example of a doc that has just been bootstrapped but needs polish.

2023-12-05 07:51 UTC, rossbulat commented on app/src/docs/Assets/Networks/Interfaces.tsx
> +    goals: any[];
Is this just an array of strings?

```suggestion
    goals: string[];
```

2023-12-05 07:52 UTC, rossbulat commented on app/src/docs/Assets/Networks/Interfaces.tsx
> +    </>
```suggestion
      <SimpleEditor code={code} standalone />
```

2023-12-05 07:52 UTC, rossbulat commented on app/src/docs/Assets/Networks/Interfaces.tsx
> +    </>
```suggestion
    <SimpleEditor code={code} standalone />
```

2023-12-05 07:53 UTC, rossbulat commented on packages/assets/.gitignore
Is this just a duplicate of the top level `.gitignore`? Why is it needed here again?

2023-12-05 07:55 UTC, rossbulat commented on packages/assets/lib/ecosystem/get_yaml_and_gen_json.js
We need to formalise this external data fetching, would probably call this folder `external` and this file representing he source of the data, like `repo.js`.

2023-12-05 08:05 UTC, rossbulat commented on packages/assets/json/Acala.json
There are 2 json folders, here and lib/ecosystem/json, it doesn't look this this is correct.

2023-12-05 08:16 UTC, wirednkod commented on packages/assets/json/Acala.json
Ahhh... Thank you! It probably is a mistake on paths. Will fix!

2023-12-05 12:48 UTC, wirednkod commented on packages/assets/.gitignore
I will remove. I was thinking to having it there in order to ignore pushed `yaml` and/or `json` dirs, but it seems preferable to just remove that "tmp" directories after build

2023-12-08 06:17 UTC, rossbulat commented on packages/assets/lib/external/json_export_index.txt
Is this file is generated by the build process? It looks like it should not belong in the source code. Like `react` currently removes the temporary index files it generates for the build, I think we can do the same here so we do not commit network info.

2023-12-08 06:17 UTC, rossbulat commented on packages/assets/lib/external/network_config.js
> +export const networks = [
Upper case camel for these consts?
```suggestion
export const POLKADOT_NETWORK_URL =
  "https://raw.githubusercontent.com/paritytech/polkadot_network_directory/master/chain_info/";

export const NETWORKS = [
```

2023-12-08 06:18 UTC, rossbulat commented on packages/assets/lib/external/polkadot_directory_repo.js
> +import fs from "fs";
To keep the codebase consistent shall we just use `fs/promises`? I found that syntax looks a lot cleaner too.

```suggestion
import fs from "fs/promises";
```

2023-12-08 06:20 UTC, rossbulat commented on packages/assets/lib/external/types.ts
> +  era?: any;
pretty sure this would be `number`

2023-12-08 06:21 UTC, rossbulat commented on packages/assets/package.json
> +    "postbuild": "rm -rf ./lib/external/yaml ./lib/external/json ./lib/external/index.ts",
```suggestion
    "postbuild": "rm -rf ./lib/external/yaml ./lib/external/json ./lib/external/index.ts .lib/external/network_config.js",
```

2023-12-08 06:22 UTC, rossbulat commented on packages/assets/lib/external/json_export_index.txt
Should be `.ts` instead of txt?

2023-12-08 10:13 UTC, wirednkod commented on packages/assets/lib/external/json_export_index.txt
This file is copied inside the tmp directory in order to have the correct structure of export. It is named `.txt` in order for linters to pass without an issue. If we completely remove it - then we need somehow to create it and I do not see any reason for not "having" it as a tmp txt that we reuse.

2024-01-04 18:21 UTC, wirednkod commented on packages/assets/lib/external/json_export_index.txt
Finally decided to remove `.txt` for avoiding confusion and leave it without any extension

2024-01-04 18:24 UTC, wirednkod commented on packages/assets/package.json
> +    "postbuild": "rm -rf ./lib/external/yaml ./lib/external/json ./lib/external/index.ts",
This is not generated. This is a file that is needed in order to use for creating the .ts file.
Instead of manually creating all the contents, e.g:
``jsx
import { NetworkInformation } from "../types";

import acalaJson from "./Acala.json";
const acala: NetworkInformation = acalaJson;

export {
  acala,
  }
  ```
  etc etc for all the networks, this file serves as a helper to use for the final dist

2024-01-16 03:08 UTC, rossbulat commented on packages/assets/lib/external/types.ts
> +  // "PoS" | "PoA" | "Aura";
Are these TODOs going to be actioned in this PR?

2024-01-16 03:09 UTC, rossbulat commented on packages/assets/lib/external/polkadot_directory_repo.js
> +const some = async (f) => {
These function names variables can be more readable.

2024-01-16 03:10 UTC, rossbulat commented on packages/assets/lib/external/polkadot_directory_repo.js
> +        "./lib/external/yaml/" + yamlFile,
This URL is in `dirs`, might be worth making it a const

2024-01-16 03:11 UTC, rossbulat commented on packages/assets/package.json
> +    "postbuild": "rm -rf ./lib/external/yaml ./lib/external/json ./lib/external/index.ts",
Yes, but we don't want to commit this file after dist is ready right?

2024-01-17 10:52 UTC, wirednkod commented on packages/assets/lib/external/types.ts
> +  // "PoS" | "PoA" | "Aura";
I want to keep these comments as guidelines. Do not want to implement in this PR though

2024-01-17 11:38 UTC, wirednkod commented on packages/assets/package.json
> +    "postbuild": "rm -rf ./lib/external/yaml ./lib/external/json ./lib/external/index.ts",
Correct. I replaced the file with code that creates that file on build

2024-02-19 13:19 UTC, closed without merging